/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/monke.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh visible={false} ref={props.meshRef} geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} />
    </group>
  )
}
useGLTF.preload('/monke.gltf')


export default React.forwardRef((props, ref) => <Model meshRef={ref} {...props}/>);
